2021-03-06T13:02:45,323 Using pip 20.2.3 from c:\users\abhay verma\appdata\local\programs\python\python39\lib\site-packages\pip (python 3.9)
2021-03-06T13:02:45,393 Non-user install because site-packages writeable
2021-03-06T13:02:45,401 Created temporary directory: C:\Users\Abhay Verma\AppData\Local\Temp\pip-ephem-wheel-cache-zzrkzvum
2021-03-06T13:02:45,402 Created temporary directory: C:\Users\Abhay Verma\AppData\Local\Temp\pip-req-tracker-y9wsgzbi
2021-03-06T13:02:45,402 Initialized build tracking at C:\Users\Abhay Verma\AppData\Local\Temp\pip-req-tracker-y9wsgzbi
2021-03-06T13:02:45,402 Created build tracker: C:\Users\Abhay Verma\AppData\Local\Temp\pip-req-tracker-y9wsgzbi
2021-03-06T13:02:45,402 Entered build tracker: C:\Users\Abhay Verma\AppData\Local\Temp\pip-req-tracker-y9wsgzbi
2021-03-06T13:02:45,404 Created temporary directory: C:\Users\Abhay Verma\AppData\Local\Temp\pip-install-jus51fno
2021-03-06T13:02:45,405 ERROR: Invalid requirement: 'gunicornweb:'
2021-03-06T13:02:45,406 Exception information:
2021-03-06T13:02:45,406 Traceback (most recent call last):
2021-03-06T13:02:45,406   File "c:\users\abhay verma\appdata\local\programs\python\python39\lib\site-packages\pip\_vendor\packaging\requirements.py", line 98, in __init__
2021-03-06T13:02:45,406     req = REQUIREMENT.parseString(requirement_string)
2021-03-06T13:02:45,406   File "c:\users\abhay verma\appdata\local\programs\python\python39\lib\site-packages\pip\_vendor\pyparsing.py", line 1955, in parseString
2021-03-06T13:02:45,406     raise exc
2021-03-06T13:02:45,406   File "c:\users\abhay verma\appdata\local\programs\python\python39\lib\site-packages\pip\_vendor\pyparsing.py", line 3814, in parseImpl
2021-03-06T13:02:45,406     raise ParseException(instring, loc, self.errmsg, self)
2021-03-06T13:02:45,406 pip._vendor.pyparsing.ParseException: Expected stringEnd, found ':'  (at char 11), (line:1, col:12)
2021-03-06T13:02:45,406 
2021-03-06T13:02:45,406 During handling of the above exception, another exception occurred:
2021-03-06T13:02:45,406 
2021-03-06T13:02:45,406 Traceback (most recent call last):
2021-03-06T13:02:45,406   File "c:\users\abhay verma\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\req\constructors.py", line 359, in parse_req_from_line
2021-03-06T13:02:45,406     req = Requirement(req_as_string)
2021-03-06T13:02:45,406   File "c:\users\abhay verma\appdata\local\programs\python\python39\lib\site-packages\pip\_vendor\packaging\requirements.py", line 100, in __init__
2021-03-06T13:02:45,406     raise InvalidRequirement(
2021-03-06T13:02:45,406 pip._vendor.packaging.requirements.InvalidRequirement: Parse error at "':'": Expected stringEnd
2021-03-06T13:02:45,406 
2021-03-06T13:02:45,406 During handling of the above exception, another exception occurred:
2021-03-06T13:02:45,406 
2021-03-06T13:02:45,406 Traceback (most recent call last):
2021-03-06T13:02:45,406   File "c:\users\abhay verma\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\cli\base_command.py", line 228, in _main
2021-03-06T13:02:45,406     status = self.run(options, args)
2021-03-06T13:02:45,406   File "c:\users\abhay verma\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\cli\req_command.py", line 182, in wrapper
2021-03-06T13:02:45,406     return func(self, options, args)
2021-03-06T13:02:45,406   File "c:\users\abhay verma\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\commands\install.py", line 294, in run
2021-03-06T13:02:45,406     reqs = self.get_requirements(args, options, finder, session)
2021-03-06T13:02:45,406   File "c:\users\abhay verma\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\cli\req_command.py", line 316, in get_requirements
2021-03-06T13:02:45,406     req_to_add = install_req_from_line(
2021-03-06T13:02:45,406   File "c:\users\abhay verma\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\req\constructors.py", line 409, in install_req_from_line
2021-03-06T13:02:45,406     parts = parse_req_from_line(name, line_source)
2021-03-06T13:02:45,406   File "c:\users\abhay verma\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\req\constructors.py", line 374, in parse_req_from_line
2021-03-06T13:02:45,406     raise InstallationError(msg)
2021-03-06T13:02:45,406 pip._internal.exceptions.InstallationError: Invalid requirement: 'gunicornweb:'
2021-03-06T13:02:45,437 WARNING: You are using pip version 20.2.3; however, version 21.0.1 is available.
2021-03-06T13:02:45,437 You should consider upgrading via the 'c:\users\abhay verma\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.
2021-03-06T13:02:45,438 Removed build tracker: 'C:\\Users\\Abhay Verma\\AppData\\Local\\Temp\\pip-req-tracker-y9wsgzbi'
